/**
 * Created by roman_b on 1/20/2017.
 */
export const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";
export const SELECT_SUB_MENU_ITEM = "SELECT_SUB_MENU_ITEM";
export const EXPAND_MENU_ITEM = "EXPAND_MENU_ITEM";
export const COLLAPSE_MENU_ITEM = "COLLAPSE_MENU_ITEM";
export const APPLY_DEFAULT_ROUTE = "APPLY_DEFAULT_ROUTE";
export const LOADING_ITEMS = "LOADING_ITEMS";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_ERROR = "LOAD_ITEMS_ERROR";

export const LOADING_SELECTED_ITEM = "LOADING_SELECTED_ITEM";
export const LOAD_SELECTED_ITEM_SUCCESS = "LOAD_SELECTED_ITEM_SUCCESS";
export const LOAD_SELECTED_ITEM_ERROR = "LOAD_SELECTED_ITEM_ERROR";
export const ITEM_NOT_FOUND = "ITEM_NOT_FOUND";

export const LOAD_TRANSLATIONS_SUCCESS = 'LOAD_TRANSLATIONS_SUCCESS';
export const LOAD_TRANSLATIONS_ERROR = 'LOAD_TRANSLATIONS_ERROR';
export const SELECT_LANG = 'SELECT_LANG';

export const SET_ROUTE_LOCATION = 'SET_ROUTE_LOCATION';

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const CHECKOUT = "CHECKOUT";
export const QUANTITY_CHANGE = "QUANTITY_CHANGE";

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const PLACE_ORDER_IN_PROGRESS = "PLACE_ORDER_IN_PROGRESS";

export const LOADING_SEARCH_ITEMS = "LOADING_SEARCH_ITEMS";
export const LOAD_SEARCH_ITEMS_SUCCESS = "LOAD_SEARCH_ITEMS_SUCCESS";
export const LOAD_SEARCH_ITEMS_ERROR = "LOAD_SEARCH_ITEMS_ERROR";
export const LOAD_PRE_SEARCH_ITEMS_SUCCESS = "LOAD_PRE_SEARCH_ITEMS_SUCCESS";