/**
 * Created by roman_b on 1/20/2017.
 */
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';
export const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";
export const SELECT_SUB_MENU_ITEM = "SELECT_SUB_MENU_ITEM";
export const EXPAND_MENU_ITEM = "EXPAND_MENU_ITEM";
export const COLLAPSE_MENU_ITEM = "COLLAPSE_MENU_ITEM";
export const APPLY_DEFAULT_ROUTE = "APPLY_DEFAULT_ROUTE";

export const INIT_LANGS = 'INIT_LANGS';
export const LOAD_TRANSLATIONS_SUCCESS = 'LOAD_TRANSLATIONS_SUCCESS';
export const LOAD_TRANSLATIONS_ERROR = 'LOAD_TRANSLATIONS_ERROR';
export const SELECT_LANG = 'SELECT_LANG';

export const SET_ROUTE_LOCATION = 'SET_ROUTE_LOCATION';

export const DATA_LOAD_ACTIONS = [LOAD_CATEGORIES_SUCCESS];
